// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/index":{"path":"guide","id":"docs/guide/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout"},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout"},"components/Drawer/index":{"id":"components/Drawer/index","path":"components/drawer","parentId":"DocLayout"},"components/dropDown/index":{"id":"components/dropDown/index","path":"components/drop-down","parentId":"DocLayout"},"components/modal/index":{"id":"components/modal/index","path":"components/modal","parentId":"DocLayout"},"components/space/index":{"id":"components/space/index","path":"components/space","parentId":"DocLayout"},"components/switch/index":{"id":"components/switch/index","path":"components/switch","parentId":"DocLayout"},"components/tag/index":{"id":"components/tag/index","path":"components/tag","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
<<<<<<< HEAD
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/docs/guide/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/button/index.md')),
'components/Drawer/index': React.lazy(() => import(/* webpackChunkName: "Drawer__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/Drawer/index.md')),
'components/dropDown/index': React.lazy(() => import(/* webpackChunkName: "dropDown__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/dropDown/index.md')),
'components/modal/index': React.lazy(() => import(/* webpackChunkName: "modal__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/modal/index.md')),
'components/space/index': React.lazy(() => import(/* webpackChunkName: "space__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/space/index.md')),
'components/switch/index': React.lazy(() => import(/* webpackChunkName: "switch__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/switch/index.md')),
'components/tag/index': React.lazy(() => import(/* webpackChunkName: "tag__index.md" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/src/tag/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
=======
<<<<<<< HEAD
'404': React.lazy(() => import(/* webpackChunkName: "E:__MyProject_Web__Rabbit组件库开发__rabbit-ui__node_modules__dumi__dist__client__pages__404" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/docs/guide/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/button/index.md')),
'components/Drawer/index': React.lazy(() => import(/* webpackChunkName: "Drawer__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/Drawer/index.md')),
'components/dropDown/index': React.lazy(() => import(/* webpackChunkName: "dropDown__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/dropDown/index.md')),
'components/modal/index': React.lazy(() => import(/* webpackChunkName: "modal__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/modal/index.md')),
'components/space/index': React.lazy(() => import(/* webpackChunkName: "space__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/space/index.md')),
'components/switch/index': React.lazy(() => import(/* webpackChunkName: "switch__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/switch/index.md')),
'components/tag/index': React.lazy(() => import(/* webpackChunkName: "tag__index.md" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/src/tag/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "E:__MyProject_Web__Rabbit组件库开发__rabbit-ui__node_modules__dumi__dist__client__pages__Demo__index" */'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
=======
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'D:/Desktop/rabbit-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'D:/Desktop/rabbit-ui/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'D:/Desktop/rabbit-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'D:/Desktop/rabbit-ui/docs/guide/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/Desktop/rabbit-ui/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'D:/Desktop/rabbit-ui/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'D:/Desktop/rabbit-ui/src/button/index.md')),
'components/Drawer/index': React.lazy(() => import(/* webpackChunkName: "Drawer__index.md" */'D:/Desktop/rabbit-ui/src/Drawer/index.md')),
'components/dropDown/index': React.lazy(() => import(/* webpackChunkName: "dropDown__index.md" */'D:/Desktop/rabbit-ui/src/dropDown/index.md')),
'components/modal/index': React.lazy(() => import(/* webpackChunkName: "modal__index.md" */'D:/Desktop/rabbit-ui/src/modal/index.md')),
'components/space/index': React.lazy(() => import(/* webpackChunkName: "space__index.md" */'D:/Desktop/rabbit-ui/src/space/index.md')),
'components/switch/index': React.lazy(() => import(/* webpackChunkName: "switch__index.md" */'D:/Desktop/rabbit-ui/src/switch/index.md')),
'components/tag/index': React.lazy(() => import(/* webpackChunkName: "tag__index.md" */'D:/Desktop/rabbit-ui/src/tag/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'D:/Desktop/rabbit-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
>>>>>>> dev_cws
>>>>>>> 8333b0f6ff5fc4177c3e68b675d6ece013b01fbe
},
  };
}
