// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
<<<<<<< HEAD
export * from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/dist/client/theme-api/index.js';
=======
export * from 'D:/Desktop/rabbit-ui/node_modules/dumi/dist/client/theme-api/index.js';
>>>>>>> 684761717a0019dbbae743b56ef700466a11effc
