// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'D:/code/Rabbit UI/rabbit-ui/node_modules/dumi/theme-default/slots/Content/index.js';
=======
export { default } from 'D:/rabbit UI/node_modules/dumi/theme-default/slots/Content/index.js';
>>>>>>> 88258c4778d2956ace6c6329b5847ea9c6f532e7
