// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'D:/桌面/rabbit-ui/node_modules/dumi/theme-default/slots/Footer/index.js';
=======
export { default } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/slots/Footer/index.js';
>>>>>>> 806764e6f35d92032663741beca54715f548a055
