// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'D:/rabbit UI/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
=======
<<<<<<< HEAD
export { default } from 'D:/code/Rabbit UI/rabbit-ui/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
=======
<<<<<<< HEAD
export { default } from 'D:/桌面/rabbit-ui/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
=======
export { default } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
>>>>>>> 806764e6f35d92032663741beca54715f548a055
>>>>>>> e174c19be5a59556575d20c66923a6f8dd32c12f
>>>>>>> dev
