// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/slots/NotFound/index.js';
=======
export { default } from 'D:/Desktop/rabbit-ui/node_modules/dumi/theme-default/slots/NotFound/index.js';
>>>>>>> 684761717a0019dbbae743b56ef700466a11effc
