// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/slots/SearchResult/index.js';
=======
export { default } from 'D:/Desktop/rabbit-ui/node_modules/dumi/theme-default/slots/SearchResult/index.js';
>>>>>>> d10a81420b0a45802b312fba20bc50d3b5b2a957
