// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/theme-default/slots/SearchResult/index.js';
=======
export { default } from 'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/theme-default/slots/SearchResult/index.js';
>>>>>>> e9fa1244043001700162506b00f236fe3f5c4495
