// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
=======
export { default } from 'D:/Desktop/rabbit-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'D:/Desktop/rabbit-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
>>>>>>> dev_cws
