// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { filesMeta, tabs } from '.';
<<<<<<< HEAD
import deepmerge from 'D:/rabbit UI/node_modules/deepmerge';
=======
<<<<<<< HEAD
import deepmerge from 'D:/code/Rabbit UI/rabbit-ui/node_modules/deepmerge';
=======
<<<<<<< HEAD
import deepmerge from 'D:/桌面/rabbit-ui/node_modules/deepmerge';
=======
import deepmerge from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/deepmerge';
>>>>>>> 806764e6f35d92032663741beca54715f548a055
>>>>>>> e174c19be5a59556575d20c66923a6f8dd32c12f
>>>>>>> dev
export const patchRoutes = ({ routes }) => {
  Object.values(routes).forEach((route) => {
    if (filesMeta[route.id]) {
      if (process.env.NODE_ENV === 'production' && (route.meta?.frontmatter?.debug || filesMeta[route.id].frontmatter.debug)) {
        // hide route in production which set hide frontmatter
        delete routes[route.id];
      } else {
        // merge meta to route object
        route.meta = deepmerge(route.meta, filesMeta[route.id]);

        // apply real tab data from id
        route.meta.tabs = route.meta.tabs?.map(id => ({
          ...tabs[id],
          meta: filesMeta[id],
        }));
      }
    }
  });
}
