// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { history } from 'dumi';
import React, { useState, useLayoutEffect, useCallback, type ReactNode } from 'react';
<<<<<<< HEAD
import { RawIntlProvider, createIntl, createIntlCache } from 'D:/桌面/rabbit-ui/node_modules/react-intl';
import { useIsomorphicLayoutEffect } from 'D:/桌面/rabbit-ui/node_modules/dumi/dist/client/theme-api/utils.js'
=======
import { RawIntlProvider, createIntl, createIntlCache } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/react-intl';
import { useIsomorphicLayoutEffect } from 'C:/Users/82068/Desktop/rabbit-UI/rabbit-ui/node_modules/dumi/dist/client/theme-api/utils.js'
>>>>>>> 806764e6f35d92032663741beca54715f548a055
import { locales, messages } from './config';

const cache = createIntlCache();

const LocalesContainer: FC<{ children: ReactNode }> = (props) => {
  const getIntl = useCallback(() => {
    const matched = locales.slice().reverse().find((locale) => (
      'suffix' in locale
        // suffix mode
        ? history.location.pathname.replace(/([^/])\/$/, '$1').endsWith(locale.suffix)
        // base mode
        : history.location.pathname.replace(/([^/])\/$/, '$1').startsWith(locale.base)
    ));
    const locale = matched ? matched.id : locales[0].id;

    return createIntl({ locale, messages: messages[locale] || {} }, cache);
  }, []);
  const [intl, setIntl] = useState(() => getIntl());

  useIsomorphicLayoutEffect(() => {
    return history.listen(() => {
      setIntl(getIntl());
    });
  }, []);

  return <RawIntlProvider value={intl} key={intl.locale}>{props.children}</RawIntlProvider>;
}

export function i18nProvider(container: Element) {
  return React.createElement(LocalesContainer, null, container);
}
