// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/code/Rabbit UI/rabbit-ui/node_modules/dumi/theme-default/builtins/Badge/index.js';
