// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/MyProject_Web/Rabbit组件库开发/rabbit-ui/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
